name: Build ReSharp3DS Studio

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y mono-complete

      - name: Install dependencies
        run: yarn install

      - name: Build Linux package
        run: yarn dist:linux

      - name: Upload Linux package
        uses: actions/upload-artifact@v4
        with:
          name: ReSharp3DS-Studio-linux
          path: electron-app/dist/ReSharp3DS-Studio-linux-x64.deb

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: yarn install

      - name: Build Windows setup
        run: yarn dist:win

      - name: Upload Windows setup
        uses: actions/upload-artifact@v4
        with:
          name: ReSharp3DS-Studio-windows
          path: electron-app/dist/ReSharp3DS-Studio-windows-x64-setup.exe
